# Generated by Django 4.1.7 on 2023-05-17 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_fournisseur_produitc_rename_img_produit_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=datetime.date(2023, 5, 17), null=True),
        ),
    ]
